<?php

/**
 * @author Nicolas CARPi <nico-git@deltablot.email>
 * @copyright 2023 Nicolas CARPi
 * @see https://www.elabftw.net Official website
 * @license AGPL-3.0
 * @package elabftw
 */

declare(strict_types=1);

namespace Elabftw\Make;

use Elabftw\Elabftw\TimestampResponse;
use Elabftw\Exceptions\ImproperActionException;
use Elabftw\Interfaces\CreateUploadParamsInterface;
use Elabftw\Interfaces\MakeTrustedTimestampInterface;
use ZipArchive;
use Override;

use function sprintf;

/**
 * Timestamp an experiment with RFC 3161 protocol: https://www.ietf.org/rfc/rfc3161.txt
 * Originally based on: https://d-mueller.de/blog/dealing-with-trusted-timestamps-in-php-rfc-3161/
 */
abstract class AbstractMakeTrustedTimestamp extends AbstractMakeTimestamp implements MakeTrustedTimestampInterface
{
    /**
     * Create a zip archive with the timestamped data and the asn1 token
     * 
     * This is WHERE the JSON and ASN1 files are assembled for timestamp export:
     * 
     * Assembly Process:
     * 1. Data file (JSON/PDF): Generated by AbstractMakeTimestamp::generateData()
     *    - For JSON: Uses MakeFullJson to create complete entity export
     *    - For PDF: Uses MakeTimestampPdf with PDF/A format
     *    - Saved to temporary file at $tsResponse->dataPath
     * 
     * 2. ASN1 Token file: Created by TimestampUtils during timestamp() process
     *    - OpenSSL creates timestamp request from data file
     *    - Request sent to Timestamp Authority (TSA)
     *    - TSA returns ASN.1 DER encoded timestamp token
     *    - Token saved to temporary file at $tsResponse->tokenPath
     * 
     * 3. Final Assembly: Both files packaged into timestamped ZIP archive
     *    - Data file renamed: 20220210171842-timestamp.(json|pdf)
     *    - Token file renamed: 20220210171842-timestamp.asn1
     *    - Both files added to: 20220210171842-timestamp.zip
     */
    #[Override]
    public function saveTimestamp(TimestampResponse $tsResponse, CreateUploadParamsInterface $create): int
    {
        // e.g. 20220210171842-timestamp.zip
        $zipName = $create->getFileName();
        // e.g. 20220210171842-timestamp.(json|pdf) - the actual data being timestamped
        $dataName = str_replace('zip', $this->dataFormat->value, $zipName);
        // e.g. 20220210171842-timestamp.asn1 - the RFC 3161 timestamp token
        $tokenName = str_replace('zip', 'asn1', $zipName);

        // update timestamp on the experiment
        $this->updateTimestamp($this->formatResponseTime($tsResponse->getTimestampFromResponseFile()));

        // ASSEMBLY POINT: Create final ZIP archive containing both JSON/PDF and ASN1 files
        $ZipArchive = new ZipArchive();
        $ZipArchive->open($create->getFilePath(), ZipArchive::CREATE);
        // Add the timestamped data file (JSON or PDF)
        $ZipArchive->addFile($tsResponse->dataPath, $dataName);
        // Add the ASN.1 timestamp token from the TSA
        $ZipArchive->addFile($tsResponse->tokenPath, $tokenName);
        $ZipArchive->close();
        return $this->entity->Uploads->create($create, isTimestamp: true);
    }

    /**
     * Return the needed parameters to request/verify a timestamp
     *
     * @return array<string,string>
     */
    #[Override]
    abstract public function getTimestampParameters(): array;

    /**
     * Convert the time found in the response file to the correct format for sql insertion
     */
    protected function formatResponseTime(string $timestamp): string
    {
        $time = strtotime($timestamp);
        if ($time === false) {
            throw new ImproperActionException(sprintf('Could not format response time from timestamp: %s', $timestamp));
        }
        return date('Y-m-d H:i:s', $time);
    }
}
